name: Docker CI

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'pynanopore/**'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jaybfn/pynanopore:latest

      - name: Update Docker Hub Description
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/pynanopore
          README_FILEPATH: './README.md'
        run: |
          README_CONTENT="$(<"${README_FILEPATH}")"
          echo "${README_CONTENT}" | \
          curl -s -X PATCH \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT ${DOCKERHUB_TOKEN}" \
            --data-raw '{"full_description": "'"${README_CONTENT//$'\n'/\\n}"'"}' \
            "https://hub.docker.com/v2/repositories/${DOCKERHUB_REPOSITORY}/"
